### ISSUE TITLE
Please add chromium

### ISSUE THREAD

**Issue by khozaei** [just-install/registry#114]
Please add chromium, it has only google-chrome app

**Comment by lvillani** [comment]
As far as I know, Google doesn't provide stable Chromium releases anywhere on the Chromium project website (only development snapshots). I'm strongly against providing a Chromium build from an unknown third party unless they have stellar reputation and someone else audited what goes in those builds. Because of this, I don't see us adding Chromium any time soon, unfortunately.

**Comment by khozaei** [comment]
Here is Chromium for scoop project.
https://github.com/lukesampson/scoop-extras/blob/master/bucket/chromium.json

**Comment by lvillani** [comment]
Scoop downloads Chromium from a third party.
