### ISSUE TITLE
openssh: wrong install location 

### ISSUE THREAD

**Issue by longtth** [just-install/registry#119]
as Google, the openssh bin should be places in `%WINDIR%\System32\OpenSSH`

>Binaries are installed to `%WINDIR%\System32\OpenSSH`. Configuration file (sshd_config) and host keys are installed to  `%ProgramData%\ssh` (only after the server is started for the first time).

But after install OpenSSH using just-install, I found the binaries stored in `C:\Program Files\OpenSSH`. 

Could you have a look on it? 

Moreover, in the OpenSSH folder installed by just-install, there is no `ssh.exe`, just these files: 
```
ssh-add.exe
ssh-agent.exe
ssh-host-config
ssh-keygen.exe
ssh-keyscan.exe
```

![image](https://user-images.githubusercontent.com/1010849/52210007-3fbdaf00-28b8-11e9-8772-a933b637d41a.png)

**Comment by tlm-2501** [comment]
This is not a bug and can be closed. It's simply two different distributions of the same software.

The version of OpenSSH distributed by just-install is a third-party *server* package. You would not find a `ssh.exe` in it, because `ssh.exe` is the OpenSSH *client*. The actual server binary is located under `C:\Program Files\OpenSSH\usr\sbin\sshd.exe` in this version. The thing that you found a description of is a built-in Windows feature on Windows 10, that can be enabled via the `Settings > Apps > Manage optional features` menu.

**Comment by geek1011** [comment]
OK, I had a look myself and can confirm. Thanks.
