### ISSUE TITLE
Skype broken

### ISSUE THREAD

**Issue by guiweber** [just-install/registry#80]
Looks like the MSI is not offered anymore. The new install executable has a pop-up that points to the windows store.

**Comment by cyagon** [comment]
https://answers.microsoft.com/en-us/skype/forum/skype_win10-skype_startms-skype_installms/skype-msi-version/3fe89f1e-abe5-44c1-b207-a4756ae7ecec

**Comment by cyagon** [comment]
MS released a "new" executable based on innosetup: https://go.skype.com/windows.desktop.download
Currently this "new" executable cant be executed on Win10, since this setup asks you to download skype from the windows app store and then closes.

I removed skype for now: https://github.com/just-install/registry/commit/0dce10bc4e52c05df083a1d46e9ec8ff158bd088

**Comment by guiweber** [comment]
Thanks. Lets close this for now.
